OPENALEX_URL_PREFIX = "https://openalex.org/"
TAXONOMY_FIELDS = ("domain", "field", "subfield", "topic")

XLSX_TO_INTERNAL_COLUMN_MAP = {
    "OpenAlex ID": "openalex_id",
    "Journal": "journal_title",
    "Publisher Name": "journal_publisher",
    "Country": "journal_country",
    "SciELO collection acronym": "scielo_collection_acronym",
    "SciELO Thematic Areas": "scielo_thematic_areas",
    "CAPES agricultural sciences": "capes_agricultural_sciences",
    "CAPES applied social sciences": "capes_applied_social_sciences",
    "CAPES biological sciences": "capes_biological_sciences",
    "CAPES engineering": "capes_engineering",
    "CAPES exact and earth sciences": "capes_exact_and_earth_sciences",
    "CAPES health sciences": "capes_health_sciences",
    "CAPES human sciences": "capes_human_sciences",
    "CAPES linguistics letters and arts": "capes_linguistics_letters_and_arts",
    "CAPES multidisciplinary": "capes_multidisciplinary",
    "CAPES Life Sciences": "capes_life_sciences",
    "CAPES Humanities": "capes_humanities",
    "CAPES Phys., Tech. Multidisc. Sciences": "capes_phys_tech_multidisc_sciences",
    "is SciELO": "is_scielo",
    "is Scopus": "is_scopus",
    "is WOS": "is_wos",
    "is AHCI": "is_ahci",
    "is ESCI": "is_esci",
    "is SCIE": "is_scie",
    "is SSCI": "is_ssci",
    "is DOAJ": "is_doaj",
    "is LILACS": "is_lilacs",
    "is Redalyc": "is_redalyc",
    "is MEDLINE": "is_medline",
    "is PMC": "is_pmc",
    "is OpenAlex": "is_openalex",
    "is Qualis": "is_qualis",
    "YEAR": "publication_year",
    "SciELO Active and Valid in the Year": "scielo_active_valid",
}

METADATA_FLAG_COLUMNS = [
    "capes_agricultural_sciences",
    "capes_applied_social_sciences",
    "capes_biological_sciences",
    "capes_engineering",
    "capes_exact_and_earth_sciences",
    "capes_health_sciences",
    "capes_human_sciences",
    "capes_linguistics_letters_and_arts",
    "capes_multidisciplinary",
    "capes_life_sciences",
    "capes_humanities",
    "capes_phys_tech_multidisc_sciences",
    "is_scielo",
    "is_scopus",
    "is_wos",
    "is_ahci",
    "is_esci",
    "is_scie",
    "is_ssci",
    "is_doaj",
    "is_lilacs",
    "is_redalyc",
    "is_medline",
    "is_pmc",
    "is_openalex",
    "is_qualis",
    "scielo_active_valid",
]

METADATA_TEXT_COLUMNS = [
    "journal_title",
    "journal_publisher",
    "journal_country",
    "scielo_collection_acronym",
    "scielo_thematic_areas",
]

CSV_METADATA_COLUMNS = [
    "journal_publisher",
    "journal_country",
    "scielo_collection",
    "scielo_thematic_areas",
    "capes_agricultural_sciences",
    "capes_applied_social_sciences",
    "capes_biological_sciences",
    "capes_engineering",
    "capes_exact_and_earth_sciences",
    "capes_health_sciences",
    "capes_human_sciences",
    "capes_linguistics_letters_and_arts",
    "capes_multidisciplinary",
    "capes_life_sciences",
    "capes_humanities",
    "capes_phys_tech_multidisc_sciences",
    "is_scielo",
    "is_scopus",
    "is_wos",
    "is_ahci",
    "is_esci",
    "is_scie",
    "is_ssci",
    "is_doaj",
    "is_lilacs",
    "is_redalyc",
    "is_medline",
    "is_pmc",
    "is_openalex",
    "is_qualis",
    "is_journal_oa",
]
